//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("\"Pure\" Xamarin.Forms Tabs (no renderers). Segmented control, bottombar tabs, mate" +
    "rial tabs, underlined tabs, scrollable tabs, badges...")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyProduct("Tabs")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2021")]
[assembly: System.Reflection.AssemblyFileVersion("2.2.0")]
[assembly: System.Reflection.AssemblyVersion("2.2.0")]
[assembly: System.Reflection.AssemblyTitle("Sharpnado.Tabs.UWP")]


