//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiSample.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SillyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SillyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiSample.Localization.SillyResources", typeof(SillyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here folks..
        /// </summary>
        internal static string Empty_Screen {
            get {
                return ResourceManager.GetString("Empty_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;It&apos;s not me, it&apos;s the back office.&quot;.
        /// </summary>
        internal static string Error_Business {
            get {
                return ResourceManager.GetString("Error_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t reach the Internet..
        /// </summary>
        internal static string Error_Network {
            get {
                return ResourceManager.GetString("Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;An ill wind is blowing...&quot;.
        /// </summary>
        internal static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETRY.
        /// </summary>
        internal static string ErrorButton_Retry {
            get {
                return ResourceManager.GetString("ErrorButton_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error thrown.
        /// </summary>
        internal static string ErrorType_Network {
            get {
                return ResourceManager.GetString("ErrorType_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data returned.
        /// </summary>
        internal static string ErrorType_NoData {
            get {
                return ResourceManager.GetString("ErrorType_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Error.
        /// </summary>
        internal static string ErrorType_None {
            get {
                return ResourceManager.GetString("ErrorType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Exception thrown.
        /// </summary>
        internal static string ErrorType_Server {
            get {
                return ResourceManager.GetString("ErrorType_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error thrown.
        /// </summary>
        internal static string ErrorType_Unknown {
            get {
                return ResourceManager.GetString("ErrorType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATCH ON YOUTUBE.
        /// </summary>
        internal static string SillyDude_GoToSource {
            get {
                return ResourceManager.GetString("SillyDude_GoToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Grid.
        /// </summary>
        internal static string SillyInfiniteGridPeople_Title {
            get {
                return ResourceManager.GetString("SillyInfiniteGridPeople_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Emulation.
        /// </summary>
        internal static string SillyPeople_ErrorEmulation {
            get {
                return ResourceManager.GetString("SillyPeople_ErrorEmulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRID MODE.
        /// </summary>
        internal static string SillyPeople_GoToGrid {
            get {
                return ResourceManager.GetString("SillyPeople_GoToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORIZONTAL LIST VIEW.
        /// </summary>
        internal static string SillyPeople_HorizontalListView {
            get {
                return ResourceManager.GetString("SillyPeople_HorizontalListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFINITE LIST VIEW.
        /// </summary>
        internal static string SillyPeople_InfiniteListView {
            get {
                return ResourceManager.GetString("SillyPeople_InfiniteListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SILLY DUDE OF THE DAY.
        /// </summary>
        internal static string SillyPeople_SillyOfTheDay {
            get {
                return ResourceManager.GetString("SillyPeople_SillyOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASK LOADER VIEW.
        /// </summary>
        internal static string SillyPeople_TaskLoaderView {
            get {
                return ResourceManager.GetString("SillyPeople_TaskLoaderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpnado.
        /// </summary>
        internal static string SillyPeople_Title {
            get {
                return ResourceManager.GetString("SillyPeople_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag&apos;N&apos;Drop.
        /// </summary>
        internal static string SortSillyPeople_Title {
            get {
                return ResourceManager.GetString("SortSillyPeople_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILMOGRAPHY.
        /// </summary>
        internal static string Tabs_Filmography {
            get {
                return ResourceManager.GetString("Tabs_Filmography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        internal static string Tabs_Grid {
            get {
                return ResourceManager.GetString("Tabs_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Tabs_Home {
            get {
                return ResourceManager.GetString("Tabs_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string Tabs_List {
            get {
                return ResourceManager.GetString("Tabs_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEME.
        /// </summary>
        internal static string Tabs_Meme {
            get {
                return ResourceManager.GetString("Tabs_Meme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUOTE.
        /// </summary>
        internal static string Tabs_Quote {
            get {
                return ResourceManager.GetString("Tabs_Quote", resourceCulture);
            }
        }
    }
}
