//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("\"Pure\" Xamarin.Forms Tabs (no renderers). Segmented control, bottombar tabs, unde" +
    "rlined tabs, scrollable tabs, badges...")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyProduct("Tabs")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2021")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.0")]
[assembly: System.Reflection.AssemblyVersion("2.1.0")]
[assembly: System.Reflection.AssemblyTitle("Sharpnado.Tabs.iOS")]


