//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Tabs")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyDescription("\"Pure\" Xamarin.Forms Tabs (no renderers).")]
[assembly: System.Reflection.AssemblyProduct("Tabs")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2020")]
[assembly: System.Reflection.AssemblyVersion("2.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.0")]


