//
// From https://raw.githubusercontent.com/davidbritch/xamarin-forms/master/ItemSelectedBehavior/ItemSelectedBehavior/Converters/SelectedItemEventArgsToSelectedItemConverter.cs
//
// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using System.Globalization;

namespace MauiSample.Presentation.Converters
{
    public class SelectedItemEventArgsToSelectedItemConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var eventArgs = value as SelectedItemChangedEventArgs;
            return eventArgs.SelectedItem;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}
